# Generated by Django 3.0.4 on 2020-03-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='Artist name')),
                ('activity_count', models.IntegerField(verbose_name='Activity count')),
                ('rating', models.FloatField()),
                ('similarity_technique', models.CharField(choices=[('Jaccard', 'Jaccard'), ('Coseno', 'Coseno'), ('Pearson', 'Pearson')], max_length=50)),
                ('model_type', models.CharField(choices=[('User user', 'User User'), ('Item item', 'Item Item')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='User ID')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('registered_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SongActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='Artist name')),
                ('track_name', models.CharField(max_length=150, verbose_name='Track name')),
                ('timestamp', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_activities', to='core.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('artist_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbours', to='core.ArtistRating')),
            ],
        ),
        migrations.AddField(
            model_name='artistrating',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_ratings', to='core.UserProfile'),
        ),
    ]
