# Generated by Django 3.0.4 on 2020-03-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200308_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistrating',
            name='similarity_technique',
            field=models.CharField(choices=[('jaccard', 'Jaccard'), ('cosine', 'Cosine'), ('pearson', 'Pearson')], max_length=50),
        ),
        migrations.CreateModel(
            name='ArtistActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=120, verbose_name='Artist name')),
                ('activity_count', models.PositiveIntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists_activities', to='core.UserProfile')),
            ],
        ),
    ]
