# Generated by Django 3.0.4 on 2020-03-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200309_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistrating',
            name='activity_count',
        ),
        migrations.RemoveField(
            model_name='artistrating',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='artistrating',
            name='similarity_technique',
        ),
    ]
